[tool.poetry]
name = "tadpoles"
version = "0.1.0"
description = ""
authors = ["Colin Hofer <colin.hofer@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
polars = "^0.20.19"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
